//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouchPadHandwriting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HandwritingExampleCharacter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HandwritingExampleCharacter() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TouchPadHandwriting.Resources.HandwritingExampleCharacter", typeof(HandwritingExampleCharacter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;ArrayOfArrayOfPoint xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;ArrayOfPoint&gt;
        ///    &lt;Point&gt;
        ///      &lt;X&gt;442&lt;/X&gt;
        ///      &lt;Y&gt;16&lt;/Y&gt;
        ///    &lt;/Point&gt;
        ///    &lt;Point&gt;
        ///      &lt;X&gt;448&lt;/X&gt;
        ///      &lt;Y&gt;19&lt;/Y&gt;
        ///    &lt;/Point&gt;
        ///    &lt;Point&gt;
        ///      &lt;X&gt;452&lt;/X&gt;
        ///      &lt;Y&gt;29&lt;/Y&gt;
        ///    &lt;/Point&gt;
        ///    &lt;Point&gt;
        ///      &lt;X&gt;461&lt;/X&gt;
        ///      &lt;Y&gt;39&lt;/Y&gt;
        ///    &lt;/Point&gt;
        ///    &lt;Point&gt;
        ///      &lt;X&gt;471&lt;/X&gt;
        ///      &lt;Y&gt;49&lt;/Y&gt;
        ///    &lt;/Point&gt;
        ///    &lt;Point&gt;
        ///      &lt;X&gt;478&lt;/X&gt;
        ///      &lt;Y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Strokes {
            get {
                return ResourceManager.GetString("Strokes", resourceCulture);
            }
        }
    }
}
