//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouchPadHandwriting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KeyNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeyNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TouchPadHandwriting.Resources.KeyNames", typeof(KeyNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backspace.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps Lock.
        /// </summary>
        internal static string Capital {
            get {
                return ResourceManager.GetString("Capital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esc.
        /// </summary>
        internal static string Esc {
            get {
                return ResourceManager.GetString("Esc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Control.
        /// </summary>
        internal static string LControlKey {
            get {
                return ResourceManager.GetString("LControlKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Feed.
        /// </summary>
        internal static string LineFeed {
            get {
                return ResourceManager.GetString("LineFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Alt.
        /// </summary>
        internal static string LMenu {
            get {
                return ResourceManager.GetString("LMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Shift.
        /// </summary>
        internal static string LShiftKey {
            get {
                return ResourceManager.GetString("LShiftKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Windows Logo.
        /// </summary>
        internal static string LWin {
            get {
                return ResourceManager.GetString("LWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Down.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Up.
        /// </summary>
        internal static string PageUp {
            get {
                return ResourceManager.GetString("PageUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Control.
        /// </summary>
        internal static string RControlKey {
            get {
                return ResourceManager.GetString("RControlKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Alt.
        /// </summary>
        internal static string RMenu {
            get {
                return ResourceManager.GetString("RMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Shift.
        /// </summary>
        internal static string RShiftKey {
            get {
                return ResourceManager.GetString("RShiftKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Windows Logo.
        /// </summary>
        internal static string RWin {
            get {
                return ResourceManager.GetString("RWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacebar.
        /// </summary>
        internal static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab.
        /// </summary>
        internal static string Tab {
            get {
                return ResourceManager.GetString("Tab", resourceCulture);
            }
        }
    }
}
